# Generated by Django 5.1.3 on 2024-11-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('youtube', 'YouTube'), ('telegram', 'Telegram'), ('instagram', 'Instagram')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ball', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_ball', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiber_security.users')),
            ],
        ),
    ]
