# Generated by Django 5.1.3 on 2024-11-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0003_ball_instagram_ball_ball_telegram_ball_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiber_security.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiber_security.users')),
            ],
        ),
    ]
