# Generated by Django 5.1.3 on 2024-11-09 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0003_remove_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='is_first_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiber_security.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
