# Generated by Django 5.1.3 on 2024-11-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0004_remove_users_username_users_is_first_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=255)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiber_security.users')),
            ],
        ),
    ]
