# Generated by Django 5.1.3 on 2024-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0006_question_test_answer_question_test_useranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserTestSession',
        ),
    ]
