# Generated by Django 5.1.3 on 2024-11-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0007_useranswer_answer_useranswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiber_security.test'),
        ),
    ]
