# Generated by Django 5.1.3 on 2025-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0010_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/image/'),
        ),
    ]
