# Generated by Django 5.1.3 on 2025-01-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiber_security', '0011_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/image/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/prize/'),
        ),
    ]
